    version: '3.8'

    services:
      backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        container_name: daodao-backend
        restart: always
        env_file:
          - .env
        volumes:
          - backend_data:/app/data
        ports:
          - "127.0.0.1:8000:8000"

      frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        container_name: daodao-frontend
        restart: always
        volumes:
          - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "127.0.0.1:8080:80"
        depends_on:
          - backend

    volumes:
      backend_data: