version: '3'

services:
  backend:
    build: ./DaoDao
    container_name: daodao-backend
    restart: always
    environment:
      - DATABASE_URL=sqlite:///data/daodao.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: daodao-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend